# Based on https://github.com/just-the-docs/just-the-docs/blob/13a1ac2a42e666227e3145e80f030b574f5d496d/_config.yml
title: "Y-Foundry Wiki"
description: The details are in the document.
logo: "/assets/images/horizontal_logo_orange-white.png"
color_scheme: yfd

# Local Setting
baseurl: ""
url: ""

# Theme
theme: "just-the-docs"
#remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3

# Aux links for the upper right navigation
aux_links:
  "Medium":
    - "//medium.com/@yfoundry/"
  "Discord":
    - "//discord.gg/yfd"
  "Twitter": 
    - "//twitter.com/YFoundryDAO"
  "Telegram":
    - "//t.me/yfoundrydao"
  "Github":
    - "//github.com/Y-Foundry-DAO/"
  "Website":
    - "//yfoundry.io/"

aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
#back_to_top: true
#back_to_top_text: "Back to top"

footer_content: ""

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit in Github"
gh_edit_repository: "https://github.com/Y-Foundry-DAO/yfd-wiki" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-default-layout
  - jemoji